version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      # PBRP_BRANCH: ''
      VERSION: '2.9.1'
      VENDOR: 'Micromax'
      CODENAME: 'Q350'
      BUILD_LUNCH: 'omni_Q350-userdebug'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: ''
      # EXTRA_CMD: ''
      PB_ENGLISH: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'android-6.0'
